// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SamadhiEstesi.Data;

#nullable disable

namespace SamadhiEstesi.Migrations
{
    [DbContext(typeof(sistema_gestion_completoContext))]
    partial class sistema_gestion_completoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SamadhiEstesi.Modelos.AntecedentesMedico", b =>
                {
                    b.Property<int>("IdAntecedente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_antecedente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAntecedente"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_registro");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo");

                    b.HasKey("IdAntecedente")
                        .HasName("PK__antecede__3E014641ED9C5608");

                    b.HasIndex(new[] { "IdPersona" }, "IX_antecedentes_medicos_id_persona");

                    b.ToTable("antecedentes_medicos", (string)null);
                });

            modelBuilder.Entity("SamadhiEstesi.Modelos.Asistencium", b =>
                {
                    b.Property<int>("IdAsistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_asistencia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsistencia"), 1L, 1);

                    b.Property<DateTime>("FechaAsistencia")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_asistencia");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.Property<string>("Observacion")
                        .HasColumnType("text")
                        .HasColumnName("observacion");

                    b.HasKey("IdAsistencia")
                        .HasName("PK__asistenc__D0454A9AD6C35D52");

                    b.HasIndex(new[] { "IdPersona" }, "IX_asistencia_id_persona");

                    b.ToTable("asistencia", (string)null);
                });

            modelBuilder.Entity("SamadhiEstesi.Modelos.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersona"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("direccion");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("rut");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("telefono");

                    b.HasKey("IdPersona")
                        .HasName("PK__persona__228148B0216803C0");

                    b.HasIndex(new[] { "IdRol" }, "IX_persona_id_rol");

                    b.ToTable("persona", (string)null);
                });

            modelBuilder.Entity("SamadhiEstesi.Modelos.RegistrosHistorico", b =>
                {
                    b.Property<int>("IdRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_registro");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRegistro"), 1L, 1);

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("accion");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.HasKey("IdRegistro")
                        .HasName("PK__registro__48155C1F8A77FA5E");

                    b.HasIndex(new[] { "IdPersona" }, "IX_registros_historicos_id_persona");

                    b.ToTable("registros_historicos", (string)null);
                });

            modelBuilder.Entity("SamadhiEstesi.Modelos.Role", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"), 1L, 1);

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nombre_Rol");

                    b.HasKey("IdRol")
                        .HasName("PK__roles__6ABCB5E0439298AF");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("SamadhiEstesi.Modelos.Rutina", b =>
                {
                    b.Property<int>("IdRutina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rutina");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRutina"), 1L, 1);

                    b.Property<string>("Comentario")
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<string>("Descripción")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripción");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.HasKey("IdRutina")
                        .HasName("PK__rutinas__A284966765C0F60A");

                    b.HasIndex(new[] { "IdPersona" }, "IX_rutinas_id_persona");

                    b.ToTable("rutinas", (string)null);
                });

            modelBuilder.Entity("SamadhiEstesi.Modelos.Suscripcione", b =>
                {
                    b.Property<int>("IdSuscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_suscripcion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSuscripcion"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Periodicidad")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("periodicidad");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor");

                    b.HasKey("IdSuscripcion")
                        .HasName("PK__suscripc__4E8926BBA03D3B62");

                    b.ToTable("suscripciones", (string)null);
                });

            modelBuilder.Entity("SamadhiEstesi.Modelos.Token", b =>
                {
                    b.Property<int>("IdToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_token");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdToken"), 1L, 1);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_expiracion");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.Property<string>("Token1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token");

                    b.HasKey("IdToken")
                        .HasName("PK__tokens__3C2FA9C4B13EA927");

                    b.HasIndex(new[] { "IdPersona" }, "IX_tokens_id_persona");

                    b.ToTable("tokens", (string)null);
                });

            modelBuilder.Entity("SamadhiEstesi.Modelos.AntecedentesMedico", b =>
                {
                    b.HasOne("SamadhiEstesi.Modelos.Persona", "IdPersonaNavigation")
                        .WithMany("AntecedentesMedicos")
                        .HasForeignKey("IdPersona")
                        .IsRequired()
                        .HasConstraintName("FK__anteceden__id_pe__4BAC3F29");

                    b.Navigation("IdPersonaNavigation");
                });

            modelBuilder.Entity("SamadhiEstesi.Modelos.Asistencium", b =>
                {
                    b.HasOne("SamadhiEstesi.Modelos.Persona", "IdPersonaNavigation")
                        .WithMany("Asistencia")
                        .HasForeignKey("IdPersona")
                        .IsRequired()
                        .HasConstraintName("FK__asistenci__id_pe__412EB0B6");

                    b.Navigation("IdPersonaNavigation");
                });

            modelBuilder.Entity("SamadhiEstesi.Modelos.Persona", b =>
                {
                    b.HasOne("SamadhiEstesi.Modelos.Role", "IdRolNavigation")
                        .WithMany("Personas")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK__persona__id_rol__3B75D760");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("SamadhiEstesi.Modelos.RegistrosHistorico", b =>
                {
                    b.HasOne("SamadhiEstesi.Modelos.Persona", "IdPersonaNavigation")
                        .WithMany("RegistrosHistoricos")
                        .HasForeignKey("IdPersona")
                        .IsRequired()
                        .HasConstraintName("FK__registros__id_pe__4E88ABD4");

                    b.Navigation("IdPersonaNavigation");
                });

            modelBuilder.Entity("SamadhiEstesi.Modelos.Rutina", b =>
                {
                    b.HasOne("SamadhiEstesi.Modelos.Persona", "IdPersonaNavigation")
                        .WithMany("Rutinas")
                        .HasForeignKey("IdPersona")
                        .IsRequired()
                        .HasConstraintName("FK__rutinas__id_pers__48CFD27E");

                    b.Navigation("IdPersonaNavigation");
                });

            modelBuilder.Entity("SamadhiEstesi.Modelos.Token", b =>
                {
                    b.HasOne("SamadhiEstesi.Modelos.Persona", "IdPersonaNavigation")
                        .WithMany("Tokens")
                        .HasForeignKey("IdPersona")
                        .IsRequired()
                        .HasConstraintName("FK__tokens__id_perso__3E52440B");

                    b.Navigation("IdPersonaNavigation");
                });

            modelBuilder.Entity("SamadhiEstesi.Modelos.Persona", b =>
                {
                    b.Navigation("AntecedentesMedicos");

                    b.Navigation("Asistencia");

                    b.Navigation("RegistrosHistoricos");

                    b.Navigation("Rutinas");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("SamadhiEstesi.Modelos.Role", b =>
                {
                    b.Navigation("Personas");
                });
#pragma warning restore 612, 618
        }
    }
}
